spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: hikari
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url是mysql容器的名称 使用docker的容器内直连
    url: jdbc:mysql://mysql:3306/id_generator?serverTimezone=GMT%2B8
    username: root
    # 这个密码在docker-compose配置文件中
    password: example
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    # 迁移sql脚本文件名称的前缀，默认V
    sql-migration-prefix: V
    # 迁移sql脚本文件名称的分隔符，默认2个下划线__
    sql-migration-separator: __
    # 迁移sql脚本文件名称的后缀
    sql-migration-suffixes: .sql
    # 迁移时是否进行校验，默认true
    validate-on-migrate: true
    # 当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baseline-on-migrate: true
